// Question 23: Conditional tests;
let car = "subaru";
console.log("Is car == 'subaru'? I predict True otherwise I predict False");
console.log(car == "subaru");
console.log(car == "audi");
let number = 23;
console.log("Is number === '23'? I predict True otherwise I predict False");
console.log(number === 23);
console.log(number === "23");
let country = "Pakistan";
console.log("Is country == 'Pakistan'? I predict True otherwise I predict False");
console.log(country == "Pakistan");
console.log(country == "Turkey");
let mobile = "Iphone";
console.log("Is mobile == 'Iphone'? I predict True otherwise I predict False");
console.log(mobile == "Iphone");
console.log(mobile == "Android");
let mattress = "MoltyFoam";
console.log("Is mattres == 'MoltyFoam'? I predict True otherwise I predict False");
console.log(mattress == "MoltyFoam");
console.log(mattress == "DuraFoam");
let pen = "gel pen";
console.log("Is pen == 'gel pen'? I predict True otherwise I predict False");
console.log(pen == "gel pen");
console.log(pen == "ball point");
let book = "Islamic books";
console.log("Is book == 'Islamic books'? I predict True otherwise I predict False");
console.log(book == "Islamic books");
console.log(book == "story books");
let inverterAC = "Dawlance";
console.log("Is inverterAC == 'Dawlance'? I predict True otherwise I predict False");
console.log(inverterAC == "Dawlance");
console.log(inverterAC == "Panasonic");
let programmingLanguage = "TypeScript";
console.log("Is programmingLanguage == 'TypeScript'? I predict True otherwise I predict False");
console.log(programmingLanguage == "TypeScript");
console.log(programmingLanguage == "JavaScript");
let motorCycle = "Honda";
console.log("Is motorCycle == 'Honda'? I predict True otherwise I predict False");
console.log(motorCycle == "Honda");
console.log(motorCycle == "Suzuki");
export {};
